### ISSUE TITLE
Token balance and "send" information lacks thousands separators

### ISSUE THREAD

**Issue by jasonraycroft** [OmniLayer/omniexplorer#101]
Lack of thousands separators in "Latest Transaction" tiles and balances (reserved and available) for a given address makes it hard distinguish between large amounts.  This could possibly be handled simply using the Intl.NumberFormat API.

**Comment by achamely** [comment]
@germanf we should look into styling/normalizing number displays to include separators  where applicable.

**Comment by germanf** [comment]
Sure, I'll review where we should apply it.
