### ISSUE TITLE
Omni Explorer Testnet

### ISSUE THREAD

**Issue by timka-zhm** [OmniLayer/omniexplorer#105]
Hi!
I've started a testnet OMNI node on my machine(Debian 8) with command below:
`/home/cryptodaemon/omnicore/src/omnicored -datadir=/home/cryptodaemon/.omnicoin/ -testnet -printtoconsole`

The synchronization started and keep going. Now I have 1100000+ blocks. But on the https://www.omniexplorer.info/ I see just 514K+ blocks.

There is my bitcoin.conf file's content below:
`testnet=1`
`mempoolexpiry=1`
`rpcthreads=2`
`rpcuser=user_name`
`rpcpassword=user_pass`
`txindex=1`

Where can I see a number of blocks in the Omni testnet?

**Comment by achamely** [comment]
@timka-zhm 
www.Omniexplorer.info does not currently run/display Testnet, it is running on mainnet

at this exact moment Mainnet has 514254  blocks which is what omniexplorer.info is running on
and testnet has 1288591 blocks which is what you have configured your client to run on. 

As omni runs on the bitcoin networks you can look at any existing testnet bitcoin explorer to see the current block count like https://www.blocktrail.com/tBTC
