### ISSUE TITLE
Active crowdsales items to address

### ISSUE THREAD

**Issue by marvgmail** [OmniLayer/omniexplorer#130]
In no particular order-
- [x] selecting Prod/Test ecosystem should be handled the same everywhere. Properties dropdown has choice for Prod/Test, but Active Crowdsales has the choice on the page. I expect tx list filters will also have prod/test

- [x] If Closing Datetime is always rounded to the whole minute (probably a good idea), we don't need to display seconds

- [x] Property ids should be displayed with a #, e.g. (#3)

- [x] To be consistent with other pages, Active Crowdsale pages should include "as of" information.

- [x] Include an indicator (same everywhere if possible) that datetimes are UTC. maybe an (i) button next to the column heading/label

- [x] on Crowdsales page,Tokens Bought is always the same as Tokens Created, even when some have been created for the issuer (e.g. #28)

- [x] on Crowdsales page, default sort order should be chronological by close datetime so users can see what will close next. Also allow sort up/down by each column.

- [x] On Crowdsales page, change Accepted Property to Buy With. These properties should be URLs to corresponding property details.

- [x] Make Rate a separate column, with a column heading that it is the number of tokens received per unit paid. (Not sure what the words should be)

- [x] Include a Buy with Omniwallet button for each row on the Crowdsales page.

- [x] on https://dt45325.omniexplorer.info/crowdsale/332 , the total sold by the tx doesn't match the Tokens Already Bought in the Active Crowdsale box on the right.

- [x] on that page, the bonus amount (+281.658862433862%) looks highly suspicious. Also, does it need the +?

- [x] also on that page, the amount for the issuer (29.582036949) has 9 decimal digits,it should be rounded (or truncated - I don't recall) to 8 decimal digits.

- [x] also on that same page, change Asset to the term we use elsewhere

- [x] on https://dt45325.omniexplorer.info/crowdsale/28 , why  does it use the k notation for quantities? That's not used anywhere else, is it?

- [x] make the layout of the items in the Asset History the same as in other tx lists

- [x] does the Asset History paginate for a long list?

- [x] do other lists include the number of items in the list, Asset History does. If that stays, move the right parenthesis so it's like (4 transactions)

- [x] if a property is divisible, include .00 in display of integer amounts so it's obvious that it's divisible.

- [x] it's not intuitively obvious that tx 51 (Create Property - Variable) means a crowdsale

- [x] On tx page, e.g. https://dt45325.omniexplorer.info/tx/c7591e401f9eb58f68d0a30150953fd4ae3ee566ceba00d99dded5b41c14b9bd#collapseAmountData "Click here for raw transaction ..." displays json. Is that the raw transaction or a json representation of it?

- [x] On that same tx page, why is there a toggle to show the amounts?

- [x] A much broader issue is that txtype 0 is a Crowdsale Purchase in this context, but it's a Simple Send when there's no active crowdsale at the recipient address.

**Comment by germanf** [comment]
@marvgmail @achamely 

* on https://dt45325.omniexplorer.info/crowdsale/332 , the total sold by the tx doesn't match the Tokens Already Bought in the Active Crowdsale box on the right.
  * The data is given by the API / @achamely 

* on https://dt45325.omniexplorer.info/crowdsale/28 , why does it use the k notation for quantities? That's not used anywhere else, is it?
  * This is a legacy format from the previous OE, and it's for readability improvement.
* make the layout of the items in the Asset History the same as in other tx lists
  * The shown data are different, that is for the layout is not the same.

* does the Asset History paginate for a long list?
  * The asset history show the full list of transactions without pagination.
    * The feature can be added in other release

*  it's not intuitively obvious that tx 51 (Create Property - Variable) means a crowdsale
  * Did you mean to hide that transaction type?

* On tx page, e.g. https://dt45325.omniexplorer.info/tx/c7591e401f9eb58f68d0a30150953fd4ae3ee566ceba00d99dded5b41c14b9bd#collapseAmountData "Click here for raw transaction ..." displays json. Is that the raw transaction or a json representation of it?
  * It's a json representation of the raw transaction, and it's the way to refer to that kind of data.

* A much broader issue is that txtype 0 is a Crowdsale Purchase in this context, but it's a Simple Send when there's no active crowdsale at the recipient address.
  * Could you provide some more information with layout and requested data to shown?

**Comment by achamely** [comment]
@germanf @marvgmail 

> on https://dt45325.omniexplorer.info/crowdsale/332 , the total sold by the tx doesn't match the Tokens Already Bought in the Active Crowdsale box on the right.
 the crowdsale value from the json 'tokensissued' is the total tokens bought by users + the total tokens issued to the issuer as any bonus. We probably need to relabel that field accordingly or subtract the issuer tokens from this amount

**Comment by marvgmail** [comment]
@germanf 
we don't use k notation elsewhere, so we shouldn't use it here.

in crowdsales list, remove :00 in datetime (just need minutes precision)

For crowdsale tx history, change the oldest tx description to <token name> crowdsale started, rather than <token name> was created. Remove the parentheses around the number of transactions.

in general - either all or none of displays of lists should show the number of items in the list. Currently, some do and some don't

add the token icon next to the token name

OW refers to the ecosystems as Production and Test, OE and OW should use the same terms

where are the token details, e.g. divisible/indivisible? that should be on the crowdsale/<spid> page

in Properties pulldown, group menu items by ecosystem

**Comment by marvgmail** [comment]
@germanf 
- [ ] In the OE menu bar - remove the 2 eco systems, put back Properties. In its dropdown: Production, Test. For each of those, the dropdown should be Property List, Crowdsales

- [ ] on the Crowdsales page, list Active Crowdsales, then a separate list of Closed Crowdsales below. For closed crowdsales, change "Buy with" column heading to "Bought with"; remove the "Buy with OW" button. (related - should it be Open Crowdsales rather than Active???)

On the crowdsale detail page:
- [ ] use the same format & content as on the asset/<propertyid> page, including warning about duplicate/similar name

On the asset page:
- [ ] include the countdown box if that asset has an active crowdsale.

- [ ] include a link (TBD) to the Property History page. This new page will list all the transactions that affected the property, in reverse chronological order.

- [ ] fit the countdown box under the property icon. The countdown box doesn't have to be so big.

- [ ] In the countdown box, the early bird bonus percentage needs at most 3 non-zero decimal digits, e.g. 12.345, 0.123, 0.00123

- [ ] in the countdown box, replace "You can participate ..." with "Share this page ..."

- [ ] on all pages, if possible don't use the "no icon" icon if there isn't one. just leave that space empty. If there has to be an icon, it should be very light gray so it's not distracting.

**Comment by mighj** [comment]
Huii9
