### ISSUE TITLE
Problem with transaction

### ISSUE THREAD

**Issue by munesu180290** [OmniLayer/omniexplorer#153]
I made a withdrawal of 96USDT from my binance account into coincola. Unfortunately did not notice that the minimum deposit was 100USDT now I cannot find the funds. Is there a way to get the funds.

the Txid is :  741c788c566ebd5acfd57a4e74512a633887f72a340a19557efdbb794cb24f9a

**Comment by achamely** [comment]
@munesu180290  Omniexplorer is just a block explorer for the Omni protocol. We do not have any control over any transfers. 
You will need to contact coincola and ask them to return the funds
