### ISSUE TITLE
tx list number of pages is off by one

### ISSUE THREAD

**Issue by marvgmail** [OmniLayer/omniexplorer#189]
See https://www.omniexplorer.info/address/154LKAnBRP6nh1qx6LNY5JcvD65bCpCH6M/8

Notice there are only 4 tx's on this page so it's the last page, but the list heading and the page navigation says there are 9 pages.

**Comment by achamely** [comment]
found the issue, it has to do with matched dex trades and their data in the db. 
page counts are calulated from the addressesintx table (which has the matched trade address reference. 
tx lists are pulled from txjson table which appears to not have the corresponding tx. Looking into fixes
