### ISSUE TITLE
Incorrect indexing

### ISSUE THREAD

**Issue by phuongnd08** [OmniLayer/omniexplorer#193]
This txid 25fecb36df77ae7030b90a24e3a1fa23aa0e8e88aceb3c7bfed39cc37eb6ac91 is indexed correct inside the node but show as error not found on omniexplorer: https://omniexplorer.info/tx/25fecb36df77ae7030b90a24e3a1fa23aa0e8e88aceb3c7bfed39cc37eb6ac91

**Comment by achamely** [comment]
@phuongnd08 the issue was related to a backend process that locked up and caused our parsing engine to lag behind for several hours. The issue is now resolved and the tx information is accessible as expected.
