### ISSUE TITLE
Transaction didn't picked by omniexplorer

### ISSUE THREAD

**Issue by caffeinum** [OmniLayer/omniexplorer#197]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Somehow this transaction, formed using input-output and OP_RETURN, does not show up or update Omni balances.

https://api.blockcypher.com/v1/btc/main/txs/bceb03c0121c45a47b27123af034f0418ef6df6643e445e2f3dc3c4c7b7df38e?limit=50&includeHex=true

## Steps to reproduce

https://api.blockcypher.com/v1/btc/main/txs/bceb03c0121c45a47b27123af034f0418ef6df6643e445e2f3dc3c4c7b7df38e?limit=50&includeHex=true

https://www.omniexplorer.info/search/bceb03c0121c45a47b27123af034f0418ef6df6643e445e2f3dc3c4c7b7df38e

# Versions

- Env: JavaScript
- Explorer: omniexplorer
- Browser:  Chrome

**Comment by dexX7** [comment]
Hi @caffeinum,

I looked into this and it seems like the parsing of the payload failed. Your payload:

```
6f6d6e69000000000000001f03473bc0
```

Without marker and seperated to highlight each part:

```
0000 0000 0000001 f03473bc0
```

It's too short, given that a normal simple send payload has 16 bytes:

- 2 byte transaction type
- 2 byte version
- 4 byte token id
- 8 byte amount

In your case the amount is only 4 bytes long.

**Comment by caffeinum** [comment]
Thanks for the head up!

My problem was I was building hex payload using JS, and it failed when I pass `.55` there.

```javascript
const toPaddedHexString = (num, len) => {
    const str = num.toString(16)
    return "0".repeat(len - str.length) + str
}

amount = toPaddedHexString(0.55 * 100000000, 31) // = 0.55 USDT
```

I fixed that adding Math.floor:
```javascript
amount = toPaddedHexString(Math.floor(0.55 * 100000000), 31) // = 0.55 USDT
```
