### ISSUE TITLE
issues with USDT transaction in BTC

### ISSUE THREAD

**Issue by jossdem** [OmniLayer/omniexplorer#198]
Hello, 

I had a problem with one of my transaction USDT in BTC 2 days ago. I send in my BINANCE wallet 996USDT and I receive only 0,00000546 BTC. I talk with the BINANCE support  team  and they told me to solve the problem with Omni support team.
Could you please help me with that issue ?
Sincerely

Jossdem

**Comment by achamely** [comment]
@jossdem please see the FAQ
https://github.com/OmniLayer/omniexplorer/wiki/OmniExplorer-FAQ
