### ISSUE TITLE
Format Balance Value

### ISSUE THREAD

**Issue by ninjatechdev** [OmniLayer/omniexplorer#213]
@germanf Can you help me to format "VALUE" /v2/address/addr/ correctly

api result : 62667876348000000
actual balance : 626,678,763.48 
```
OST /v2/address/addr/ HTTP/1.1
Host: api.omniwallet.org
Content-Type: application/x-www-form-urlencoded
Content-Type: application/x-www-form-urlencoded

addr=1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA&addr=1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw
```

**Comment by germanf** [comment]
Hi, the balance value retrieved by the service is padded to 8 zeros to right (decimal places), where 626678763`48000000` are decimals.
