### ISSUE TITLE
omni explorer doesnot show BTC Available Balance but https://www.blockchain.com/zh/btc/address/1HXB3gHZFG6cgxBa5hucV3PETG3hTCax7y show the balance

### ISSUE THREAD

**Issue by ying2025** [OmniLayer/omniexplorer#246]
omni explorer doesnot show BTC Available Balance but https://www.blockchain.com/zh/btc/address/1HXB3gHZFG6cgxBa5hucV3PETG3hTCax7y show the balance

**Comment by achamely** [comment]
@ying2025 this appears to be an intermittent issue as refreshing the page after a few moments displays the correct btc balance. We are looking into it

**Comment by achamely** [comment]
@ying2025 this should be a little better handled for now
