### ISSUE TITLE
get Confiremed

### ISSUE THREAD

**Issue by mohammadbax98** [OmniLayer/omniexplorer#247]
Hello
for example
this two link
https://www.omniexplorer.info/tx/1026c81a7dc5a52e9b8563d6a5c1574e899467f523d16dc16d6b9452b4ee24d8
https://www.omniexplorer.info/tx/f641c18f98b242a791c3e3a06661474794ac27d196b02704179a36a8c6234737

first one is confiremed. how can i check with api the transaction is confiremed or not? in json details i can't find value about it

**Comment by achamely** [comment]
@mohammadbax98  In the json data returned by the api you need to check the 'confirmations' field. As the transaction gets confirmations on the network that field increases. 
Also remember that you need to also check the status of a confirmed transaction to see if its actually valid or not
