### ISSUE TITLE
I already have 3.5 hours no confirmation in the transaction. 

### ISSUE THREAD

**Issue by Provizor-071** [OmniLayer/omniexplorer#268]
I already have 3.5 hours no confirmation in the transaction. before this was not. This time I sent USDT with Huobi. What is the reason for such a long transaction?

https://www.omniexplorer.info/search/c9dd1d750a2fe33a44edde34f91427ab0fb805b85494fa81ec02a7ba65a093b3

**Comment by achamely** [comment]
The fee per byte paid by the sender is lower then the current network average https://bitcoinfees.earn.com/ 
--
Size | 257 (bytes)
Fees | 0.0000189 BTC
Fee per byte | 7.354 sat/B

You'll have to wait for the network to pick it up and it may take several more hours.

**Comment by Provizor-071** [comment]
8 hours have passed, and the transaction has not yet begun! Why do you allow such low commissions? Other exchangers do not have these problems. I need to do 4 more transactions. Can there also be long lasting transactions? Let me compensate for this!26.03.2019, 21:38, "Adam" <notifications@github.com>:The fee per byte paid by the sender is lower then the current network average https://bitcoinfees.earn.com/
Size | 257 (bytes)
Fees | 0.0000189 BTC
Fee per byte | 7.354 sat/B
You'll have to wait for the network to pick it up and it may take several more hours.

**Comment by Provizor-071** [comment]
Based on this link https://bitcoinfees.earn.com/, you set a commission 5 times lower than the average! It says that the average is 9,216 satoshi, and your total is 1890.26.03.2019, 21:38, "Adam" <notifications@github.com>:The fee per byte paid by the sender is lower then the current network average https://bitcoinfees.earn.com/
Size | 257 (bytes)
Fees | 0.0000189 BTC
Fee per byte | 7.354 sat/B
You'll have to wait for the network to pick it up and it may take several more hours.

**Comment by Provizor-071** [comment]
I'm going to do 4 more transactions! Make a normal commission, not a Jewish one! Don't be a goon26.03.2019, 21:38, "Adam" <notifications@github.com>:The fee per byte paid by the sender is lower then the current network average https://bitcoinfees.earn.com/
Size | 257 (bytes)
Fees | 0.0000189 BTC
Fee per byte | 7.354 sat/B
You'll have to wait for the network to pick it up and it may take several more hours.

**Comment by achamely** [comment]
@Provizor-071 we do not have any control over the miner fee that a sender chooses. Just like bitcoin transactions, that is controlled entirely by the sender when creating the transaction
