### ISSUE TITLE
v2/address/addr/ endpoint returning "This endpoint accepts at most 20 addresses" regardless of number of addresses

### ISSUE THREAD

**Issue by Marreck** [OmniLayer/omniexplorer#272]
The following request, as per the example at https://api.omniexplorer.info/#doc-api-detail, returns the error "This endpoint accepts at most 20 addresses" instead of the correct result

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Content-Type: application/x-www-form-urlencoded" -d "addr=1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA&addr=1KYiKJEfdJtap9QX2v9BXJMpz2SfU4pgZw" "https://api.omniwallet.org/v2/address/addr/"`

**Comment by achamely** [comment]
@Marreck the issue is fixed and the endpoint is working as documented now
