### ISSUE TITLE
WITHDRAWAL TO WRONG ADDRESS

### ISSUE THREAD

**Issue by anasalgabsi94** [OmniLayer/omniexplorer#273]
I SENT 400 USDT TO THE WRONG ADDRESS WHICH IS >> BTC << ADDRESS NOT >> USDT << ADDRESS. 
HOW IT WAS CONFIRMED IT IS WRONG ADDRESS NOT FOR USDT BUT FOR BTC AND THE BTC ADDRESS FOR YOU AS BINANCE SO THIS IS INTERNAL ISSUE IN BINANCE NOT OUTSIDE. 
RECEIVER BTC ADDRESS: 3PNcGqdyh8x1A1oVtJ6JXwp4RToHKRcgd5 
SENDER USDT ADDRESS: 1FoWyxwPXuj4C6abqwhjDWdz6D4PZgYRjA[](url)

**Comment by achamely** [comment]
The Omnilayer uses the bitcoin network which means bitcoin addresses are valid destinations. Unless the receiving wallet supports the omni protocol you will need to manually recover the funds off the receiving address : https://github.com/OmniLayer/omniwallet/wiki/Recovering-funds-from-a-Segwit-Address

**Comment by quangdaidws** [comment]
I SENT 180.2 USDT TO THE WRONG ADDRESS WHICH IS >> BCH << ADDRESS NOT >> USDT << ADDRESS.
HOW TO GET BACK MY MONEY ? PLEASE HELP ME 
RECEIVER BCH ADDRESS: 1Aoexn64dx5nWjkMJikTdBbwRZu6myYuFe
SENDER USDT ADDRESS: 3NrEXrB9qAxXYfRt6jKtBD8QzoU2qtNWDR

**Comment by jagbara1** [comment]
can you help me recover the USDT sent to btc pls
