### ISSUE TITLE
Withdraw to wrong address

### ISSUE THREAD

**Issue by quangdaidws** [OmniLayer/omniexplorer#275]
I SENT 180.2 USDT TO THE WRONG ADDRESS WHICH IS >> BCH << ADDRESS NOT >> USDT << ADDRESS.
HOW TO GET BACK MY MONEY ? PLEASE HELP ME
RECEIVER BCH ADDRESS: 1Aoexn64dx5nWjkMJikTdBbwRZu6myYuFe
SENDER USDT ADDRESS: 3NrEXrB9qAxXYfRt6jKtBD8QzoU2qtNWDR

**Comment by achamely** [comment]
@quangdaidws The Omnilayer uses the bitcoin network. 
You will need the private key for the receiving address 1Aoexn64dx5nWjkMJikTdBbwRZu6myYuFe to recover the funds.
Once you have the private key you can simply import it into a new or existing omniwallet account to access the funds: https://github.com/OmniLayer/omniwallet/wiki/Importing-a-Private-Key-into-Omniwallet.org

**Comment by quangdaidws** [comment]
how to get back money from address 1Aoexn64dx5nWjkMJikTdBbwRZu6myYuFe
