### ISSUE TITLE
Incorrect URL for MaidSafeCoin

### ISSUE THREAD

**Issue by david-maidsafe** [OmniLayer/omniexplorer#280]
## Issue Type

- [ ] Bug (https://github.com/OmniLayer/omniexplorer/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/OmniLayer/omniexplorer/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

The URL displayed on the [MaidSafeCoin page](https://omniexplorer.info/asset/3) is incorrect.
Currently it shows: www.buysafecoins.com 
This should be: https://www.safenetwork.tech

Suggested change: replace www.buysafecoins.com with www.safenetwork.tech.

Screenshot:
[![omnibug.png](https://i.postimg.cc/hjBsnBRB/omnibug.png)](https://postimg.cc/4KWVvj3L)

## Steps to reproduce

- visit (https://omniexplorer.info/asset/3)
- observe incorrect URL (www.buysafecoins.com)
- click on URL = page not found/

**Comment by achamely** [comment]
@david-maidsafe this is not a bug. Property data is pulled from the blockchain and when maidsafe as created the url used was buysafecoins.com. 
At the moment we do not have a way for issuers to update the blockchain property data after creation but we are working on a new tx type to allow this, it is just further down the development pipeline at the moment. 
As an interim option however we have placed a temporary override for omniexplorers display. 
This will not affect the data displayed in any other users client but only on omniexplorer/wallet for now. 
Once the new tx type is ready you will need to use that to update the relevant information.

**Comment by david-maidsafe** [comment]
Thanks for the response @achamely

**Comment by david-maidsafe** [comment]
Oh, Adam (@achamely)... not sure about the etiquette of asking you about another project that you may or may not know anything about but I'll chance my arm anyway.  Do you know how omni support of Tresorit is progressing. We get asked about it by our community now and again. Thanks either way, David.
