### ISSUE TITLE
Missing api for getting unspent output

### ISSUE THREAD

**Issue by idoor88** [OmniLayer/omniexplorer#285]
# Omni Explorer
I am trying to develop a wallet to send omni USDT through bitcoin blockchain, I checked your api service, I can see this api for sending transaction:
https://api.omniexplorer.info/#request-v1-transaction-pushtx, 
but before calling this API, I need to fetch utxo for the sending address, and I can not find this utxo api like this from ominexplorer.info
https://insight.bitpay.com/api/addr/${address}/utxo/
or https://blockexplorer.com/api-ref, 
So is there a utxo api from api.omniexplorer.info?

Thanks

**Comment by achamely** [comment]
@idoor88 no, omniexplorer does not provide utxo services.  
That endpoint is for pushing/broadcasting an already created/signed transaction
Creating and signing the transaction, including the retrieval of utxo information, needs to be handled by the user outside of the api.

**Comment by idoor88** [comment]
Hi Achamely, thanks for your response, does that mean I can use this api from bitpay:
https://insight.bitpay.com/api/addr/${address}/utxo/ to get the unspent outputs and sign it, then use the omni explorer api: 
https://api.omniexplorer.info/v1/transaction/pushtx/ to broadcast the transaction?

Thanks
