### ISSUE TITLE
Tether transfer problem

### ISSUE THREAD

**Issue by tunay06** [OmniLayer/omniexplorer#292]
the tether transfer I made was invalid. param disappeared in the system 70usdt.
https://omniexplorer.info/tx/4d43d4f7dfeb6a1657afedde0dda55e6771906ae4aac1200f7424d3e7eb152a0

**Comment by achamely** [comment]
The transaction was rejected from the blockchain network and as such was pruned/removed. 
There is nothing more to do for that tx. If it was a withdrawal from an exchange contact them and ask them to reprocess your request as the previous tx is no longer on the network
