### ISSUE TITLE
Sending with pushtx call is so slow

### ISSUE THREAD

**Issue by herokuapp88** [OmniLayer/omniexplorer#303]
Hi All, I have a question, when I send a few USDT via the /pushtx from one omniwallet address to another, it takes a long time even days to show up the transactions, they do not even show up on this site: 
https://omniexplorer.info/address/1Nwci1hvtQLJZuHH5yyPjZrfXLDoXL7iDQ, 
but shows up on this site as uncomfirmed: 
https://www.blockchain.com/btc/address/1Nwci1hvtQLJZuHH5yyPjZrfXLDoXL7iDQ
I increased the fee to about $2 of btc,  but still the same, any ideas what is going on? some code code look like this:

`........

                   unspentList = fetchUnspentList(fromAddress);
                    const totalUnspent = unspentList.reduce(
                         (a, b) => a + b.satoshis,
                                        0,
                         );

                // add tx input
                unspentList.forEach(({ txid, vout }) => txb.addInput(txid, vout));

                    txb.addOutput(toAddress, dustValue);
                    // add OmniLayer payload output
                    const omniPayload = genOmniPayload(toAmount);
                    txb.addOutput(omniPayload, 0); 
                    // calculate fee value
                    feeValue = calculateTxFee(txb, fromAddress, fromPrivateKey, feeRate); 
                    changeValue = totalUnspent - feeValue - dustValue;
                    feeValue = feeValue + dustValue;
                   txb.addOutput(fromAddress, changeValue);
              
                  // sign for every unspent tx
                  unspentList.forEach((unspent, index) => {
                        txb.sign(index, keyPair);
                }); 
                const txhash = txb.build().toHex();
........

function genOmniPayload(amount) {

      const hexAmount = (amount * precision)
          .toString(16)
          .padStart(16, '0')
          .toUpperCase();
      const simpleSend = [
          '6f6d6e69', // omni
          // 31 for Tether, you can modify it depends on your regtest chain
          '000000000000001f',
          hexAmount,
      ].join('');
      const data = [Buffer.from(simpleSend, 'hex')];
      const omniOutput = bitcoin.payments.embed({ data }).output;

      return omniOutput;
  }`

**Comment by achamely** [comment]
@herokuapp88  for reliability purposes we recently had to temporarily limit how unconfirmed transactions where being handled. At this time we have pushed an update that should significantly reduce the time between when a transaction is pushed and when it shows up in the unconfirmed transaction list on the addresses page
