### ISSUE TITLE
Can Omniexplorer run on Own Omni Fulll Node?

### ISSUE THREAD

**Issue by Sotatek-AnhDao** [OmniLayer/omniexplorer#306]
# Omni Explorer

I had setup Omnicore beside Bitcoin Full node, and I also see the website omniexplorer.info to look up the information of Omni on livenet. Can I config omniexplorer to display my Omni full node's information like Bitcoin insight?

**Comment by achamely** [comment]
Hello @Sotatek-AnhDao , 
The Omniexplorer website is not designed to talk directly to omnicore. 
It is designed as a frontend around our API server. 
The API Server pulls data from a backend caching server and database. 
The Database is populated with data by OmniEngine which is what talks to OmniCore. 
So there are several projects that are all interdependent to provide the data to omniexplorer
