### ISSUE TITLE
btc wallet balance is always zero

### ISSUE THREAD

**Issue by playniuniu** [OmniLayer/omniexplorer#317]
The omniexplore btc address balance is always zero

for example: https://omniexplorer.info/search/14b3FaPkBfojRvPE6A21DCyfYnymsRG4Jo

but it has btc balance

**Comment by achamely** [comment]
BTC balances are provided from blockchain lookups from your local machine and as far as we can see should be loading properly 

![image](https://user-images.githubusercontent.com/6587089/66834535-ce94c800-ef2b-11e9-928c-fdb3e39a8804.png)

If you are having issues with the btc balance please check the page load to see if you are being blocked from accessing `https://blockchain.info/balance?cors=true&active=14b3FaPkBfojRvPE6A21DCyfYnymsRG4Jo`  and let us know?

**Comment by playniuniu** [comment]
I can see the data from blockchain.info, but cannot see the data from omniexplore

<img width="1238" alt="截屏2019-10-15下午9 35 17" src="https://user-images.githubusercontent.com/790500/66836508-046d9700-ef94-11e9-90e8-771593b4c01d.png">

<img width="831" alt="截屏2019-10-15下午9 36 33" src="https://user-images.githubusercontent.com/790500/66836531-10595900-ef94-11e9-9a39-0049e62f9696.png">

**Comment by achamely** [comment]
Ahh ok i see the issue now. Seems the search page does not trigger the blockchain url balance lookup. If you click on the link that says 'click here for full address details' it should populate the balance . I'll add a tasks to fix the search page balance lookup

**Comment by playniuniu** [comment]
Thanks so much

There is another problem, your https://api.omniwallet.org/v2/address/addr/ is also zero for btc, it can only return usdt value
