### ISSUE TITLE
Outbound links on assets page aren't prefixed with http/https protocol

### ISSUE THREAD

**Issue by burnside** [OmniLayer/omniexplorer#321]
## Issue Type

Bug 

## Description

Outbound links on assets page aren't prefixed with http/https protocol

![image](https://user-images.githubusercontent.com/1981664/71024666-490fce80-20ba-11ea-8a3e-feeac37e5eb8.png)

![image](https://user-images.githubusercontent.com/1981664/71024607-254c8880-20ba-11ea-86f6-6ff61d6c5abf.png)

## Steps to reproduce

Browse to: https://www.omniexplorer.info/asset/3

Try to click outbound URL link.

# Versions

Unknown, sorry.

**Comment by germanf** [comment]
@burside Thank you for your contribution.

**Comment by germanf** [comment]
#fixed
