### ISSUE TITLE
pls help. why is omniexplorer showing invalid status for my transation??

### ISSUE THREAD

**Issue by 13riches** [OmniLayer/omniexplorer#337]
Hi,

On Omniexplorer.info , when I search the following transaction hash, the transaction status shows that the transaction is invalid and that the sender has insufficient balance.

transaction hash
3f1ef60912eb18df898ad1921ca9b2af394ce0ca351f2aea6adf24c31736d8ff

sender (1GJnY3EjNk7T8pXrfeA8tYHKh25TeJKZM7)
receiver (1Db7j1FurN5Nyj8XaER5M3KHgbCAMesATE)

The sender (1GJnY3EjNk7T8pXrfeA8tYHKh25TeJKZM7) has checked and verified that they had enough balance at the point of transaction and the explorers suggested in your guide (General questions : Omniwallet History and missing BTC transactions) showed that the transaction is valid.

According to the explorers that was suggested to check for transactions (2 links below), both explorer shows that the transaction is valid (confirmations 1510 as of today)

1)https://btc.com/3f1ef60912eb18df898ad1921ca9b2af394ce0ca351f2aea6adf24c31736d8ff
2)https://blockchair.com/bitcoin/transaction/3f1ef60912eb18df898ad1921ca9b2af394ce0ca351f2aea6adf24c31736d8ff

Please help to check on this issue (sync problem? bug? display issue?) and rectify the problem as this transaction is just hanging in the air.

**Comment by achamely** [comment]
@13riches 
There is a difference between the underlying Bitcoin transaction being valid and the Omni protocol transaction instructions being valid. 

All omni protocol transactions are sent using the bitcoin blockchain. This means that in order for any transaction to be parsed/evaluated by the Omni client it needs to be valid bitcoin transaction first. Only then can it be parsed/evaluated by the Omni Core Client for its validity on the Omni Protocol. 

In the question of your transaction above it was indeed invalid. At the time the sender attempted to send that tx their balance was only ~185 USDt, 
What appears to have happened is that in block 619242 (the block right before) the sender had a balance of ~2185 USDt.  Then in block 619242 they sent 2 txs for 2000 USDt at the same time. Yours and c7d9faaab33812c33f0af9cafe354c0fc2e1b979e85b3226ee0bec0fdf1b8220.   During the tx processing the other tx, c7d9faaab33812c33f0af9cafe354c0fc2e1b979e85b3226ee0bec0fdf1b8220, was processed first (as its position in the block was first). This caused the senders balance to drop to 185USDt and when your tx was processed/evaluated for validity it failed. 

Additionally please let your sender know they should ensure they are currently running on Omni Core 0.8 as its possible their confusion is related to a bug in a previous release: https://blog.omni.foundation/2020/03/04/omni-core-v0-8-0-released-update-required/

We are already in the process of reaching out to the other explorer to inform them of the same upgrade requirement.
