### ISSUE TITLE
Withdrawal Missing

### ISSUE THREAD

**Issue by MMoiz300** [OmniLayer/omniexplorer#367]
Hello,

I have sent USDT to BTC account mistakenly from my Binance wallet. Amount is deducted from my Binance wallet but its not received at the reciver end. Binance team has directed me to omni as i sent via this. 

Can you please assist in this regard

**Comment by achamely** [comment]
@MMoiz300 contact the omniwallet support email https://www.omniwallet.org/about/contact they can better assist
