### ISSUE TITLE
  txn-mempool-conflict    

### ISSUE THREAD

**Issue by GnWorld** [OmniLayer/omniexplorer#375]
我的一个地址（1BxQn4RXb1GqXvyzbd7hwNVpRYMhCwHAaq）发送交易数据时提示 txn-mempool-conflict   ，希望能得到您的帮助，下面是我的代码
        let host_omniexplorer = "https://api.omniexplorer.info"
        let hc = new HttpClient()
        let postdata = "signedTransaction="+hex
        hc.post(host_omniexplorer+"/v1/transaction/pushtx/",postdata)

**Comment by achamely** [comment]
@GnWorld 

txn-mempool-conflict means that one or more of the UTXO's your tx is trying to spend is already spent in a previous tx (confirmed or unconfirmed). 
If you are creating the transaction locally please make sure you keep track of the UTXO dataset that is already used. 
If you are using an external service to create the tx, then wait for any current transactions to confirm before continuing.
