### ISSUE TITLE
No deal found

### ISSUE THREAD

**Issue by helloxzt** [OmniLayer/omniexplorer#381]
160f065385f7d5f30f26735383a15490006ddab666f6d4082c96d389bc9a7bd5
This transaction of mine is not available on your block browser,But it can be found in the following block browser
https://blockchair.com/bitcoin/transaction/160f065385f7d5f30f26735383a15490006ddab666f6d4082c96d389bc9a7bd5?_search=header&_type=transaction

**Comment by achamely** [comment]
@helloxzt that is not an omni protocol transaction. OmniExplorer is a block chain explorer for Omni protocol transactions only. We do not provide block explorer services for all bitcoin transactions

**Comment by helloxzt** [comment]
Do you mean that my transaction is not from BTC?

**Comment by helloxzt** [comment]
@achamely Do you mean that my transaction is not from BTC?

**Comment by achamely** [comment]
@helloxzt I mean your transaction is not an Omni protocol Transaction. 
The Omni protocol is a subset of the bitcoin network. 
All Omni Protocol Transactions are Bitcoin transactions but Not all Bitcoin transactions are Omni Protocol transactions. 

Your transaction is only a Bitcoin transaction and as such is not going to show up on the OmniProtocol blockchain OmniExplorer
