### ISSUE TITLE
Tether transaction confirmed but not available.

### ISSUE THREAD

**Issue by concernedcryptobanker** [OmniLayer/omniexplorer#385]
Txn: 67968bb9311cf4cacd106fcd27f403be8ea1120b95e2613d1a15fd0325f66930

Using the changelly exchange in my Coinomi wallet, I transferred my BTC over to Tether(Omni). The txn has over 2000 confirmations at this point but I still don’t have access to my funds. Can this be fixed?

**Comment by achamely** [comment]
@concernedcryptobanker you need to contact changelly/Coinomi. 
Omniexplorer is just a block explorer and does not have access to or control over any funds
