### ISSUE TITLE
Usdt unconfirmed for hours

### ISSUE THREAD

**Issue by johnpaul199812** [OmniLayer/omniexplorer#389]
# Omni Explorer

Hello, I sent 41 usdt omini layer to another wallet with omini layer network
For 4 hours now it's still unconfirmed

Here is the transaction hash

b4db97a496884a8206a66f3aad4318fee6a331c40c0353c3df948b0bee413e26

Pls help me confirm it and deliver it to the omini layer address of the recipient

**Comment by achamely** [comment]
@johnpaul199812 Unfortunately we do not have any control over transaction confirmations. There is nothing we can do as this is entirely controlled by the blockchain miners. 
The miners prioritize transactions based on the network fee the transaction was sent with. As your transaction was sent with a low fee compared to the rest of the current network it has a very low priority. Unfortunately your best course of action right now is to just wait for the network to eventually process it.
