### ISSUE TITLE
usdt unconfirmed for hours

### ISSUE THREAD

**Issue by Chacblue** [OmniLayer/omniexplorer#391]
I sent 1166 usdt. For 3 hours now it's still unconfirmed.

Here is the transaction hash: 1c4a3606236010f15928bbb0f2cdfb4a8a811bc95a87f5889ee556725056cea9

please help me

**Comment by Chacblue** [comment]
i still waiting.................

**Comment by achamely** [comment]
@Chacblue transaction confirmation is controlled by the blockchain miners, not us. They determine what transactions are included in the blocks they are mining and prioritize the transactions they mine based on the transaction fee. In the past day there has been a 4x increase in pending transactions on the blockchain in total which will cause some delays in transaction confirmation (https://www.blockchain.com/charts/mempool-count).  Most of the time all you need to do is wait, during a spike in transaction volume the majority of transactions should confirm within a few more hours. Thankfully it appears your transaction has confirmed at this time
