### ISSUE TITLE
Crypto transfer error

### ISSUE THREAD

**Issue by marc3627** [OmniLayer/omniexplorer#393]
Hi yesterday I made a transaction from binance to Coinbase, with the direction of this walllet: 3D1qWhmfB9JHa94KYAvta8QBEX3LUuiWbD, but surprisingly I only've received 0,25€ from 82€. And the rest went to this wallet:
3LwP196cfYjsFVAPTSAtZW8jnr2PwdRHud. I made the transaction throughh Ovni. What can I do? Please help!

**Comment by achamely** [comment]
@marc3627 Coinbase does not currently support Tether. 
Only Coinbase would be able to recover/return them as they alone control the address the funds were sent to. 
If Coinbase is unable or unwilling to assist you with recovering/returning the funds then unfortunately your funds are stuck on the Coinbase platform until they either add support for Tether or offer a recovery option
