### ISSUE TITLE
I sent usdt to a bitcoin address how can i recover it

### ISSUE THREAD

**Issue by N0handoutz** [OmniLayer/omniexplorer#394]
I sent usdt to a bitcoin address and i only received 38 cents when i should have received 938usdt so what should i do to recover my money please help me asap

**Comment by achamely** [comment]
USDt should only be sent to an address that specifically states it supports USDt deposits. 
Sending to a BTC address could result in the funds becoming stuck/unrecoverable. 
If you have access to the private key of the receiving address you can create an account on omniwallet.org and import the private key of that address to regain access to the funds. 
If you do not have access to the private key you will need to reach out to the platform the funds were sent to and ask them to recover/return the funds to you as only they would be able to recover funds sent to their platform.
