### ISSUE TITLE
Tranfer error on OmniExplorer 

### ISSUE THREAD

**Issue by 16641989** [OmniLayer/omniexplorer#399]
# Omni Explorer

## Issue Type

Hello,

I transfered on Friday 26th, 1153.9369 USDT from Binance platform to Probit
I unfortunately copied the BTC withdrawal address to Probit : 1Q3QodVDJug3cUjtrzSAmisheragEUSEtP
The right adress for USDT is : 151RjZeu4rkqjFcNVJNpbqjX72YVteTLn1

By the way, the status is "confirmed" but my 1153.9369 USDT are stuck on OMNI Explorer
However, I only tranfered USDT but a little part of BTC has been tranfered 

My request is : Can you tranfer the USDT to the correct Probit address : 151RjZeu4rkqjFcNVJNpbqjX72YVteTLn1
Because my money is blocked and no one can use it....

Thanks in advance

## Description

![Capture Binance](https://user-images.githubusercontent.com/81559603/112826305-1b6f4e80-908d-11eb-9995-4c8f48be7c83.PNG)
![Capture Omni Explorer](https://user-images.githubusercontent.com/81559603/112826309-1c07e500-908d-11eb-9b5d-f6e5679ff75d.PNG)
![Capture Probit](https://user-images.githubusercontent.com/81559603/112826311-1c07e500-908d-11eb-9f2a-71908d88f2ce.PNG)

**Comment by achamely** [comment]
@16641989 as stated in the [FAQ](https://github.com/OmniLayer/omniexplorer/wiki/OmniExplorer-FAQ) we do not have any control over any funds. 
Your USDt are owned/controlled by the address they are currently on, which in this case is your Probit BTC deposit address. 
The ONLY recovery option is if Probit is willing to recover/return the funds manually to you. If they are not willing/able to attempt the recovery then the funds would be stuck indefinitely.
