### ISSUE TITLE
USDT Transfer issue

### ISSUE THREAD

**Issue by Srikja** [OmniLayer/omniexplorer#401]
Hi,
I have transferred 1289 USDT on March 4th 2021 from binance. Here is the transaction ID code

 1JHMPLY882RaG5FiJhnqzx4MYgNpgpucC7

It says transfer confirmed but I have received a message fr Antares that they don't accept OMNI payment. Kindly re-direct that money back to my binance wallet.

![Screenshot_20210331-114422](https://user-images.githubusercontent.com/81674412/113103725-44264e00-921d-11eb-9d2a-66d6af9e689c.jpg)
I have attached the screenshot for your reference.

Regards,
Srikanth.
srikanth.j2009@gmail.com

**Comment by Srikja** [comment]
I have also attached binance to OMNI transaction here
![Uploading Screenshot_20210327-223857.jpg…]()

**Comment by achamely** [comment]
@Srikja unfortunately there is nothing we can do. 
As stated in the [FAQ](https://github.com/OmniLayer/omniexplorer/wiki/OmniExplorer-FAQ) 
All tokens/funds are owned/controlled by the address they are currently on. Only the person/wallet/exchange which created the address and controls the private key for the address can access those funds.

You will need to contact Antares and work with them on any possible recovery options
