### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by anderduranv** [OmniLayer/omniexplorer#402]
I transfer usdt from a usdt wallet in binance to bitcoins wallet in localbitcoins! Please help, this is the txid: 

Thanks

**Comment by anderduranv** [comment]
2268ad0169144dabf43a2593e9d449dd26b8c1fdb2b32415cdfeaa7acf9e57ad

**Comment by achamely** [comment]
@anderduranv unfortunately there is nothing we can do.
As stated in the FAQ
All tokens/funds are owned/controlled by the address they are currently on. Only the person/wallet/exchange which created the address and controls the private key for the address can access those funds.

You will need to contact Local bitcoins and work with them on any possible recovery options
