### ISSUE TITLE
i send usdt to btc address

### ISSUE THREAD

**Issue by jmuc-msm** [OmniLayer/omniexplorer#407]
I made a mistake and sent usdt to a btc address, omniexplorer.info shows as confirmed, is there any way to get my funds back?

**Comment by achamely** [comment]
@jmuc-msm unfortunately there is nothing we can do.
As stated in the FAQ
All tokens/funds are owned/controlled by the address they are currently on. Only the person/wallet/exchange which created the address and controls the private key for the address can access those funds.

You will need to contact the recipient and work with them on any possible recovery options
