### ISSUE TITLE
ammar 

### ISSUE THREAD

**Issue by ammar689968** [OmniLayer/omniexplorer#413]
I sent the USDT tokens to a Bitcoin URL by mistake in these two transactions and it did not reach the way it was in the blockchain.

Transaction symbol

 5b32148ed846562e19c8bb5834184c91c9f2379b89e5341e5eb0beb05feb77d7

4e737a3f4e0f7b759cef2069085c58b24b9060ad1cc5946c5d91320acded2f09

**Comment by achamely** [comment]
@ammar689968 unfortunately there is nothing we can do.
As stated in the FAQ
All tokens/funds are owned/controlled by the address they are currently on. Only the person/wallet/exchange which created the address and controls the private key for the address can access those funds.

You will need to contact the recipient and work with them on any possible recovery options
