### ISSUE TITLE
Omni Tether transaction request 

### ISSUE THREAD

**Issue by Cryptotestbyme** [OmniLayer/omniexplorer#443]
Hello everyone, I hope to get an answer here.

We tried the api of https://api.omniexplorer.info/v1 but we couldn't find how to create a transaction request? 
I'll appreciate if you help me.

**Comment by achamely** [comment]
At this time we there are not any published public endpoints for transaction creation. 
Please take a look at Omni Core for transaction creation: 
https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction
https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md

**Comment by Cryptotestbyme** [comment]
> At this time there are not any published public endpoints for transaction creation in Omni Explorer. Please take a look at Omni Core for transaction creation: https://github.com/OmniLayer/omnicore/wiki/Use-the-raw-transaction-API-to-create-a-Simple-Send-transaction https://github.com/OmniLayer/omnicore/blob/master/src/omnicore/doc/rpc-api.md

Cool! Thank you for your answer, I'll check, hope it will help us.
