### ISSUE TITLE
Block with specific transactions (Dex order, NFT transfer) are not showing on the explorer 

### ISSUE THREAD

**Issue by ludonakamoto** [OmniLayer/omniexplorer#450]
# Omni Explorer

## Issue Type
BUG

Different blocks are not displayed on the browser list.

The block 3889850 is not displayed on the list (see picture).

The block contains one dex purchase: https://dt45325.omniexplorer.info/ftc/block/3889850

The block3889867 is not displayed on the list (see second picture).

The block contains one NFT transfer of holder https://dt45325.omniexplorer.info/ftc/block/3889867

## Description

![image](https://user-images.githubusercontent.com/91568037/138548252-78698e6b-97a1-445e-8368-9b6ca9fe0da5.png)

![image](https://user-images.githubusercontent.com/91568037/138548408-e7e6e216-008e-432f-b2bb-e3d3680e43d1.png)

## Steps to reproduce

Browse https://dt45325.omniexplorer.info/ftc/blocks/3889855

or 

https://dt45325.omniexplorer.info/ftc/blocks/3889875

# Versions

- Browser: Edge, Firefox

**Comment by Bushstar** [comment]
Fixed by https://github.com/FeatherCoin/omnifeatherengine/commit/cc849238e75d92aa60ae1f1dedde85f667b563c4
