### ISSUE TITLE
Inconsitency with NFT token balance after transfer.

### ISSUE THREAD

**Issue by ludonakamoto** [OmniLayer/omniexplorer#451]
# Omni Explorer

## Issue Type
BUG

One NFT (property #38 on FTC blockchain) has been transfer from address 38cTEpdq72kRCuAdYrZf62QXDKiyWFt5RW to 3GbFbGNvZSPMVKNranhRQEaRvWQLgpcfcQ

The balance on wallet 38cTEpdq72kRCuAdYrZf62QXDKiyWFt5RW still display 1 (instead of 0).
The balance on wallet 3GbFbGNvZSPMVKNranhRQEaRvWQLgpcfcQ show not property #38 at all (instead of 1)

## Description

![image](https://user-images.githubusercontent.com/91568037/138548753-e6c6fb4d-219d-49df-accd-7d5ae6629885.png)

![image](https://user-images.githubusercontent.com/91568037/138548769-cf7b9985-7a4a-48f1-b511-c609fd1bcb2b.png)

## Steps to reproduce

Transfer was performed in this block: https://dt45325.omniexplorer.info/ftc/block/3889867

Wallet balance available here: https://dt45325.omniexplorer.info/ftc/address/38cTEpdq72kRCuAdYrZf62QXDKiyWFt5RW
and here: https://dt45325.omniexplorer.info/ftc/address/3GbFbGNvZSPMVKNranhRQEaRvWQLgpcfcQ

# Versions

- Browser: Edge

**Comment by Bushstar** [comment]
Resolved by https://github.com/FeatherCoin/omnifeatherengine/commit/c2e1ee137b546b67a3b804b993c09cb7b022a79a
