### ISSUE TITLE
USDT WITHDRAW

### ISSUE THREAD

**Issue by Cece1919** [OmniLayer/omniexplorer#460]
![DD6D1E68-5B87-4272-9E74-B83027490D80](https://user-images.githubusercontent.com/96360790/146660951-d1ef0dcf-da87-4bbf-8a13-161a1ebb9a6b.png)

![33D13DB7-CE79-4CD6-B50F-A52756418AF4](https://user-images.githubusercontent.com/96360790/146660956-674d15b7-1653-424d-b3e3-57d1c1245122.png)
I have took a usdt withdraw from Moonxbt buy omni.
My status of the transaction is complete, but i cannot access to the details on omni (2 pictures describe my problems) and i HAVE NOT RECEIVE usdt. Please take a look at my issue. Thank you alot

**Comment by achamely** [comment]
Please contact moonxbt, the transaction id displayed in your screenshot shows as 'synchronizing' which means the exchange has not actually processed your withdrawal on the blockchain as of yet
