### ISSUE TITLE
Watch only address?

### ISSUE THREAD

**Issue by Mtaqii** [OmniLayer/omniexplorer#528]
Hello great community,

How are you all.
I'm currently facing an issue where i have transferred USDT to omni wallet. The problem is that whenever I want to transfer my money elsewhere I am stopped with a message saying that my address is watch only. 

Any solution?

**Comment by achamely** [comment]
Please check OmniWallets FAQ https://www.omniwallet.org/about/faq as well as the in Wallet help text about WatchOnly Wallets. 

If you still have questions please reach out to the OmniWallet Support team : https://www.omniwallet.org/about/contact
OmniExplorer is just a block explorer and does not handle anything related to OmniWallet.
