### ISSUE TITLE
Usdt Not received due to wrong address

### ISSUE THREAD

**Issue by Tusharusdt** [OmniLayer/omniexplorer#642]
Team, 
As I had not received mention transection BTC Due to wrong BTC address as I had mention Usdt address, 
Transection hash Details as Given Below
015263b766d5c6ecc837af05f100a3e2a74987980922e52c7295354512607a19

Kindly Suggest the process to Revert or withdraw the Asset 
If any request for revert

**Comment by achamely** [comment]
Please see the FAQs;  
[https://github.com/OmniLayer/omniexplorer/wiki/OmniExplorer-FAQ]
