### ISSUE TITLE
Why are you freezing my tokens in the tether app what gives you the right to mess with my property I'm going to sue you asshole quit fucking w my page and wallet

### ISSUE THREAD

**Issue by Neoclan45** [OmniLayer/omniexplorer#654]

**Comment by achamely** [comment]
For assistance with Tether tokens please contact Tether. 
For additional details please see the FAQ https://github.com/OmniLayer/omniexplorer/wiki/OmniExplorer-FAQ#what-can-omniexplorer-not-do
