### ISSUE TITLE
REQUEST FOR RECOVERY OF FUNDS STUCK IN ADDRESS

### ISSUE THREAD

**Issue by mateusabilio** [OmniLayer/omniexplorer#656]
Dear,

I made a transfer of 294 dollars from the "Binance" broker to the "Mercado Bitcoin" broker. However, instead of using the USDT address, I used the BTC address. Even so, the transfer was completed. Therefore, the amount is stuck at this address in dollars. I request help to recover this balance.

Adress: 1A8gWCRgEpBHLdVi93Liio1rH9tu1GXkV4

TXID: 921c9b91beb8101eee9d511ba3f0564937f672957ce2337e9cccc4920931e855

LINK OF THE TRANSACTION: https://omniexplorer.info/address/1A8gWCRgEpBHLdVi93Liio1rH9tu1GXkV4 

![WhatsApp Image 2024-11-10 at 18 00 52](https://github.com/user-attachments/assets/b551f231-207a-4765-90df-b413b963ee58)
![bitcoin](https://github.com/user-attachments/assets/c34594d5-1704-4473-8170-0c1a6b6041bd)

**Comment by Elsonbastey** [comment]
> Dear,
> 
> I made a transfer of 294 dollars from the "Binance" broker to the "Mercado Bitcoin" broker. However, instead of using the USDT address, I used the BTC address. Even so, the transfer was completed. Therefore, the amount is stuck at this address in dollars. I request help to recover this balance.
> 
> Adress: 1A8gWCRgEpBHLdVi93Liio1rH9tu1GXkV4
> 
> TXID: 921c9b91beb8101eee9d511ba3f0564937f672957ce2337e9cccc4920931e855
> 
> LINK OF THE TRANSACTION: https://omniexplorer.info/address/1A8gWCRgEpBHLdVi93Liio1rH9tu1GXkV4
> 
> ![WhatsApp Image 2024-11-10 at 18 00 52](https://private-user-images.githubusercontent.com/188052173/384905854-b551f231-207a-4765-90df-b413b963ee58.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzcwNzQsIm5iZiI6MTczMTMzNjc3NCwicGF0aCI6Ii8xODgwNTIxNzMvMzg0OTA1ODU0LWI1NTFmMjMxLTIwN2EtNDc2NS05MGRmLWI0MTNiOTYzZWU1OC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTQ1MjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY5ZjdmOWFkNTg1NTI3ZmEwNDlkODk4YWNmYmU0ZDBkYjBlYzMxNjkwODkyMTk3ZjY0YjJlNWUwNTNhNTM4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4MEz35QzRSbUyAxxog_ztsbXgY59bt-4sh03MuWPPwQ) ![bitcoin](https://private-user-images.githubusercontent.com/188052173/384905863-c34594d5-1704-4473-8170-0c1a6b6041bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzcwNzQsIm5iZiI6MTczMTMzNjc3NCwicGF0aCI6Ii8xODgwNTIxNzMvMzg0OTA1ODYzLWMzNDU5NGQ1LTE3MDQtNDQ3My04MTcwLTBjMWE2YjYwNDFiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxNDUyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjQ2NTQ3NjU1OTIzNjJkNzk5Y2Q2NzkzMDAyZWQ5Y2RmYjhkOTg0NTAzMGUyMGYxYzA5MmE2YmQ4MjcyZjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eZP5qopUsSYf1gt6PkNcZUcwyWHfLW0ZTKJDkLH4x-8)


Hello @mateusabilio 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID BTC16463 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Binance Network DApps Support Ticket Requests.](https://thedappsupport.live)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by achamely** [comment]
@mateusabilio Unfortunately once a transaction has been sent we do not have any control over it or the ability to reverse it. 
Based on your report, the only people who can access or recover the funds now will be the recipient, who you stated is "Mercado Bitcoin" broker. 
You will need to reach out to their support team, explain what happened, and request their assistance in having the funds recovered/returned. 
Unfortunately if they are unable or unwilling to assist you then their is nothing more anyone else can do (Do not be fooled by scammers) and the funds will remain stuck on the destination address.
